### ISSUE TITLE
Navbar hover menu hard to read in dark mode

### ISSUE THREAD

**Issue by sanders41** [long2ice/meilisync-web#1]
When in dark mode the user hover menu background font stays black making it hard to read.

![menu](https://github.com/long2ice/meilisync-web/assets/25045024/a8f75fa1-dbdb-464e-b056-744f72db16d3)

**Comment by sanders41** [comment]
I'm pretty sure the `text-neutral-900 shadow` [here](https://github.com/long2ice/meilisync-web/blob/9fb3db9c4ec2dfb931ce97460ee0d63305276acb/src/components/NavBar.vue#L53) is the issue. In order to test that it looks like I need to get `meilisync` and the databases running, but I haven't had a chance to do that to test.

**Comment by long2ice** [comment]
fixed
